/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/W1030/Desktop/m0/rtl/al_ip/clk_gen.v
 ** Date	:	2024 05 17
 ** TD version	:	5.6.71036
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             24.000MHz
//	Clock multiplication factor: 50
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C1        	| 150.000000MHZ	| 0  DEG     
//		C3        	| 150.000000MHZ	| 0  DEG     
//		C4        	| 120.000000MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module clk_gen (
  refclk,
  reset,
  extlock,
  clk1_out,
  clk3_out,
  clk4_out 
);

  input refclk;
  input reset;
  output extlock;
  output clk1_out;
  output clk3_out;
  output clk4_out;


  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("24.000"),
    .FEEDBK_MODE("NOCOMP"),
    .FEEDBK_PATH("VCO_PHASE_0"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(2),
    .ICP_CURRENT(9),
    .KVCO(2),
    .LPF_CAPACITOR(1),
    .LPF_RESISTOR(8),
    .REFCLK_DIV(1),
    .FBCLK_DIV(50),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(8),
    .CLKC1_CPHASE(7),
    .CLKC1_FPHASE(0),
    .CLKC3_ENABLE("ENABLE"),
    .CLKC3_DIV(8),
    .CLKC3_CPHASE(7),
    .CLKC3_FPHASE(0),
    .CLKC4_ENABLE("ENABLE"),
    .CLKC4_DIV(10),
    .CLKC4_CPHASE(9),
    .CLKC4_FPHASE(0) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(extlock),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(open),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({open, open, open, open, open, open, open, open}),
    .fbclk(1'b0),
    .clkc({clk4_out, clk3_out, open, clk1_out, open}) 
  );

endmodule

