--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/W1030/Desktop/m0/rtl/al_ip/clk_gen.vhd
 -- Date	:	2024 05 17
 -- TD version	:	5.6.71036
--------------------------------------------------------------

-------------------------------------------------------------------------------
--	Input frequency:             24.000MHz
--	Clock multiplication factor: 50
--	Clock division factor:       1
--	Clock information:
--		Clock name	| Frequency 	| Phase shift
--		C1        	| 150.000000MHZ	| 0  DEG     
--		C3        	| 150.000000MHZ	| 0  DEG     
--		C4        	| 120.000000MHZ	| 0  DEG     
-------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY eagle_macro;
USE eagle_macro.EAGLE_COMPONENTS.ALL;

ENTITY clk_gen IS
  PORT (
    refclk : IN STD_LOGIC;
    reset : IN STD_LOGIC;
    extlock : OUT STD_LOGIC;
    clk1_out : OUT STD_LOGIC;
    clk3_out : OUT STD_LOGIC;
    clk4_out : OUT STD_LOGIC 
  );
END clk_gen;

ARCHITECTURE rtl OF clk_gen IS
  SIGNAL clkc_wire :  STD_LOGIC_VECTOR (4 DOWNTO 0);
BEGIN
  pll_inst : EG_PHY_PLL
  GENERIC MAP (
    DPHASE_SOURCE => "DISABLE",
    DYNCFG => "DISABLE",
    FIN => "24.000",
    FEEDBK_MODE => "NOCOMP",
    FEEDBK_PATH => "VCO_PHASE_0",
    STDBY_ENABLE => "DISABLE",
    PLLRST_ENA => "ENABLE",
    SYNC_ENABLE => "DISABLE",
    GMC_GAIN => 2,
    ICP_CURRENT => 9,
    KVCO => 2,
    LPF_CAPACITOR => 1,
    LPF_RESISTOR => 8,
    REFCLK_DIV => 1,
    FBCLK_DIV => 50,
    CLKC1_ENABLE => "ENABLE",
    CLKC1_DIV => 8,
    CLKC1_CPHASE => 7,
    CLKC1_FPHASE => 0,
    CLKC3_ENABLE => "ENABLE",
    CLKC3_DIV => 8,
    CLKC3_CPHASE => 7,
    CLKC3_FPHASE => 0,
    CLKC4_ENABLE => "ENABLE",
    CLKC4_DIV => 10,
    CLKC4_CPHASE => 9,
    CLKC4_FPHASE => 0 
  )
  PORT MAP (
    refclk => refclk,
    reset => reset,
    stdby => '0',
    extlock => extlock,
    load_reg => '0',
    psclk => '0',
    psdown => '0',
    psstep => '0',
    psclksel => b"000",
    dclk => '0',
    dcs => '0',
    dwe => '0',
    di => b"00000000",
    daddr => b"000000",
    fbclk => '0',
    clkc => clkc_wire 
  );

  clk4_out <= clkc_wire(4);
  clk3_out <= clkc_wire(3);
  clk1_out <= clkc_wire(1);

END rtl;

